server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    consul:
     enabled: true
     discovery:
      query-passing: true
    gateway:
      routes:
        - id: multiplication
          uri: lb://multiplication/
          predicates:
          - Path=/attempts,/attempts/**,/challenges/**,/users/**

        - id: gamification
          uri: lb://gamification/
          predicates:
          - Path=/leaderboard

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
            - GET
            - POST
            - OPTIONS
      
      default-filters:
      - name: Retry
        args:
          retries: 3
          mothods: GET,POST

logging:
  level:
    'org.springframework.cloud.gateway.handler.predicate': trace

